### ISSUE TITLE
"Try it out" does not work for "getInvoice"

### ISSUE THREAD

**Issue by AndySchroder** [LightRider5/lnvpn#24]
On https://lnvpn.net/api/documentation/ "Try it out" does not work for "getInvoice". It suggests a command of `curl -X 'POST' 'https://lnvpn.net/api/v1/getInvoice' -H 'accept: */*'  -d ''` but that just results in `{"status":400,"error":"Duration missing"}'`. Instead, `curl -X 'POST' 'https://lnvpn.net/api/v1/getInvoice' -H 'accept: */*' -d 'duration=0.1'` is needed.

**Comment by LightRider5** [comment]
Hi, thanks for pointing it out. It is fixed now.
