### ISSUE TITLE
"Valid until" comment in the wireguard config file only shows the month/day and not time or year

### ISSUE THREAD

**Issue by AndySchroder** [LightRider5/lnvpn#27]
Please provide a complete expiration date and time in the config file.

**Comment by AndySchroder** [comment]
By the way, my tunnel keeps working past the complete "valid until" time shown on https://lnvpn.net/ (which comes up after I paid). So, I'm not sure if you give a grace period until the end of the day, or an extra hour, or what.

**Comment by AndySchroder** [comment]
UPDATE: looks like it stopped working after an extra hour.

**Comment by LightRider5** [comment]
Thanks for reporting this issue. It is fixed now, the expiry date is now in long date format in the conf file. The filename is still short because there is a limitation in some OS.
